// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDamX26c1mtoqcH8CgvgMurm0wa_IgsLqk',
    appId: '1:77909794333:web:d082b5bc7d8e33bb6a70f4',
    messagingSenderId: '77909794333',
    projectId: 'auth-418c7',
    authDomain: 'auth-418c7.firebaseapp.com',
    storageBucket: 'auth-418c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBjj3azxC8yWlO1Fqn00Frcz0BLgN0sA',
    appId: '1:77909794333:android:b175697fc6aec5cc6a70f4',
    messagingSenderId: '77909794333',
    projectId: 'auth-418c7',
    storageBucket: 'auth-418c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwjasLvrJcyNR_6jv2kZz952Z4MnetKA',
    appId: '1:77909794333:ios:87ba8d0577fb28ac6a70f4',
    messagingSenderId: '77909794333',
    projectId: 'auth-418c7',
    storageBucket: 'auth-418c7.appspot.com',
    iosBundleId: 'com.example.loginlogoutbasic',
  );
}
